In [ ]:
 import pandas as pd
 import numpy as np

In [ ]:
df = pd.read_csv("cairo Real-Estate-revised.csv")
df.head()

,ID,City,Location,Area,Bedrooms,Bathrooms,Floor,YearBuilt,Seller,View,Payment,Finishing,Furnished,Parking,Security,SchoolDist,Color,Price
0,EG-10001,Cairo,Shubra,120.0,2.0,3.0,3.0,2025,Developer,Street,Installments,Unfinished,Furnished,Yes,No,10.26,Beige,2069000.0
1,EG-10002,Cairo,Al-Haram,162.0,3.0,2.0,6.0,2024,Developer,Other,Installments,Unfinished,Furnished,No,Yes,9.54,Beige,2849000.0
2,EG-10003,Cairo,Al-Haram,122.0,3.0,NaN,4.0,2024,Developer,Street,Installments,Unfinished,Unfurnished,Yes,Yes,6.47,White,2461000.0
3,EG-10004,Cairo,Sheikh Zayed,212.0,4.0,3.0,13.0,2027,Broker,Garden,Installments,Finished,Unfurnished,Yes,No,13.50,Grey,13092000.0
4,EG-10005,Cairo,Maadi,NaN,2.0,1.0,6.0,2025,Developer,Garden,Installments,Finished,Unfurnished,Yes,Yes,7.84,Off-White,6254000.0

In [ ]:
df.isnull().sum()

ID              0
City            0
Location        0
Area          180
Bedrooms      178
Bathrooms     162
Floor         166
YearBuilt       0
Seller          0
View            0
Payment         0
Finishing       0
Furnished       0
Parking         0
Security        0
SchoolDist      0
Color           0
Price           0
dtype: int64

In [ ]:
missing_percentage = (df.isnull().sum() / len(df)) * 100

missing_percentage[missing_percentage > 0]

Area         3.60
Bedrooms     3.56
Bathrooms    3.24
Floor        3.32
dtype: float64

In [ ]:
numerical_columns = ['Area', 'Bedrooms', 'Bathrooms', 'Floor']

for col in numerical_columns:
    df[col] = df[col].fillna(df[col].median())

In [ ]:
df.isnull().sum()

ID            0
City          0
Location      0
Area          0
Bedrooms      0
Bathrooms     0
Floor         0
YearBuilt     0
Seller        0
View          0
Payment       0
Finishing     0
Furnished     0
Parking       0
Security      0
SchoolDist    0
Color         0
Price         0
dtype: int64

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 18 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ID          5000 non-null   object
 1   City        5000 non-null   object
 2   Location    5000 non-null   object
 3   Area        5000 non-null   float64
 4   Bedrooms    5000 non-null   float64
 5   Bathrooms   5000 non-null   float64
 6   Floor       5000 non-null   float64
 7   YearBuilt   5000 non-null   int64
 8   Seller      5000 non-null   object
 9   View        5000 non-null   object
 10  Payment     5000 non-null   object
 11  Finishing   5000 non-null   object
 12  Furnished   5000 non-null   object
 13  Parking     5000 non-null   object
 14  Security    5000 non-null   object
 15  SchoolDist  5000 non-null   float64
 16  Color       5000 non-null   object
 17  Price       5000 non-null   float64
dtypes: float64(6), int64(1), object(11)
memory usage: 703.3+ KB

In [ ]:
df.columns

Index(['ID', 'City', 'Location', 'Area', 'Bedrooms', 'Bathrooms', 'Floor',
       'YearBuilt', 'Seller', 'View', 'Payment', 'Finishing', 'Furnished',
       'Parking', 'Security', 'SchoolDist', 'Color', 'Price'],
      dtype='object')

In [ ]:
for col in df.columns:
    print(f"{col}: {df[col].nunique()} unique values")

ID: 5000 unique values
City: 1 unique values
Location: 10 unique values
Area: 255 unique values
Bedrooms: 8 unique values
Bathrooms: 6 unique values
Floor: 20 unique values
YearBuilt: 54 unique values
Seller: 7 unique values
View: 5 unique values
Payment: 2 unique values
Finishing: 2 unique values
Furnished: 2 unique values
Parking: 2 unique values
Security: 2 unique values
SchoolDist: 1454 unique values
Color: 5 unique values
Price: 3102 unique values

In [ ]:
df = df.drop(columns=['ID', 'City'], axis=1)

df.head()

,Location,Area,Bedrooms,Bathrooms,Floor,YearBuilt,Seller,View,Payment,Finishing,Furnished,Parking,Security,SchoolDist,Color,Price
0,Shubra,120.0,2.0,3.0,3.0,2025,Developer,Street,Installments,Unfinished,Furnished,Yes,No,10.26,Beige,2069000.0
1,Al-Haram,162.0,3.0,2.0,6.0,2024,Developer,Other,Installments,Unfinished,Furnished,No,Yes,9.54,Beige,2849000.0
2,Al-Haram,122.0,3.0,2.0,4.0,2024,Developer,Street,Installments,Unfinished,Unfurnished,Yes,Yes,6.47,White,2461000.0
3,Sheikh Zayed,212.0,4.0,3.0,13.0,2027,Broker,Garden,Installments,Finished,Unfurnished,Yes,No,13.50,Grey,13092000.0
4,Maadi,143.0,2.0,1.0,6.0,2025,Developer,Garden,Installments,Finished,Unfurnished,Yes,Yes,7.84,Off-White,6254000.0

In [ ]:
numerical_columns = ['Area', 'Bedrooms', 'Bathrooms', 'Floor', 'Price']

In [ ]:
for col in numerical_columns:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)

    IQR = Q3 - Q1

    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    df = df[(df[col] >= lower_bound) & (df[col] <= upper_bound)]

In [ ]:
print("Number of rows after removing outliers:", len(df))
print("Number of columns:", len(df.columns))

Number of rows after removing outliers: 4294
Number of columns: 16

In [ ]:
df.describe()

,Area,Bedrooms,Bathrooms,Floor,YearBuilt,SchoolDist,Price
count,4294.000000,4294.000000,4294.000000,4294.000000,4294.000000,4294.000000,4.294000e+03
mean,137.918724,2.472054,1.944807,2.178388,2023.176293,7.695468,5.397255e+06
std,50.478125,0.802997,0.825282,1.360087,7.655273,4.294897,2.823133e+06
min,15.000000,1.000000,1.000000,0.000000,1915.000000,0.110000,1.027000e+06
25%,99.000000,2.000000,1.000000,1.000000,2024.000000,4.052500,3.235000e+06
50%,140.000000,3.000000,2.000000,2.000000,2025.000000,7.780000,4.641500e+06
75%,170.000000,3.000000,3.000000,3.000000,2027.000000,11.340000,7.199750e+06
max,280.000000,4.000000,4.000000,6.000000,2030.000000,15.000000,1.406800e+07

In [ ]:
from sklearn.preprocessing import LabelEncoder, OrdinalEncoder

In [ ]:
df = pd.get_dummies(df, columns=['View'], dtype=int)

In [ ]:
# ordinal_encoder = OrdinalEncoder()
# df['Location'] = ordinal_encoder.fit_transform(df[['Location']])

In [ ]:
df = pd.get_dummies(df, columns=['Location'], dtype=int)

In [ ]:
label_encoder = LabelEncoder()

df['Color'] = label_encoder.fit_transform(df['Color']) + 1

In [ ]:
label_encoder = LabelEncoder()

df['Seller'] = label_encoder.fit_transform(df['Seller']) + 1

In [ ]:
df['Finishing'] = df['Finishing'].map({
    'Finished': 1,
    'Unfinished': 0
})

In [ ]:
df['Payment'] = df['Payment'].map({
    'Cash': 1,
    'Installments': 0
})

In [ ]:
df['Furnished'] = df['Furnished'].map({
    'Furnished': 1,
    'Unfurnished': 0
})

In [ ]:
df['Parking'] = df['Parking'].map({
    'Yes': 1,
    'No': 0
})

In [ ]:
df['Security'] = df['Security'].map({
    'Yes': 1,
    'No': 0
})

In [ ]:
# binary_columns = ['Furnished', 'Parking', 'Security']

# for col in binary_columns:
#     df[col] = df[col].map({
#         'Yes': 1,
#         'No': 0,
#         'Furnished': 1,
#         'Unfurnished': 0
#     })

In [ ]:
df.head(20)

,Area,Bedrooms,Bathrooms,Floor,YearBuilt,Seller,Payment,Finishing,Furnished,Parking,...,Location_6th of October,Location_Ain Shams,Location_Al-Haram,Location_Heliopolis,Location_Maadi,Location_Madinaty,Location_Nasr City,Location_New Cairo,Location_Sheikh Zayed,Location_Shubra
0,120.0,2.0,3.0,3.0,2025,5,0,0,1,1,...,0,0,0,0,0,0,0,0,0,1
1,162.0,3.0,2.0,6.0,2024,5,0,0,1,0,...,0,0,1,0,0,0,0,0,0,0
2,122.0,3.0,2.0,4.0,2024,5,0,0,0,1,...,0,0,1,0,0,0,0,0,0,0
4,143.0,2.0,1.0,6.0,2025,5,0,1,0,1,...,0,0,0,0,1,0,0,0,0,0
6,145.0,3.0,3.0,2.0,2027,1,0,0,1,1,...,1,0,0,0,0,0,0,0,0,0
7,133.0,2.0,2.0,3.0,2025,1,0,1,0,0,...,0,0,0,1,0,0,0,0,0,0
8,145.0,3.0,2.0,2.0,2025,1,1,1,0,1,...,1,0,0,0,0,0,0,0,0,0
9,125.0,3.0,2.0,4.0,2019,5,0,0,1,0,...,0,0,0,0,0,0,0,0,0,1
10,185.0,3.0,3.0,3.0,2024,1,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
11,154.0,3.0,3.0,4.0,2025,1,0,0,1,1,...,0,1,0,0,0,0,0,0,0,0
12,143.0,3.0,3.0,2.0,2027,1,0,0,1,1,...,1,0,0,0,0,0,0,0,0,0
13,160.0,3.0,3.0,2.0,2026,1,0,0,1,1,...,0,0,1,0,0,0,0,0,0,0
14,157.0,3.0,2.0,3.0,2026,1,0,0,0,1,...,0,0,1,0,0,0,0,0,0,0
15,127.0,1.0,2.0,0.0,2026,1,0,1,0,1,...,0,0,0,0,0,0,1,0,0,0
16,130.0,3.0,2.0,0.0,2027,1,0,0,1,1,...,0,1,0,0,0,0,0,0,0,0
18,115.0,1.0,1.0,0.0,2028,1,0,1,0,1,...,0,0,0,0,0,0,0,0,1,0
19,260.0,3.0,3.0,2.0,2018,1,1,1,0,1,...,0,0,0,0,0,1,0,0,0,0
21,134.0,3.0,2.0,2.0,2027,1,0,0,0,1,...,0,0,0,0,1,0,0,0,0,0
26,190.0,3.0,3.0,1.0,2025,1,1,0,0,1,...,0,0,1,0,0,0,0,0,0,0
27,200.0,3.0,2.0,2.0,2024,1,1,1,0,1,...,0,0,0,0,0,0,0,1,0,0

In [ ]:
df.dtypes

Area                       float64
Bedrooms                   float64
Bathrooms                  float64
Floor                      float64
YearBuilt                    int64
Seller                       int64
Payment                      int64
Finishing                    int64
Furnished                    int64
Parking                      int64
Security                     int64
SchoolDist                 float64
Color                        int64
Price                      float64
View_Garden                  int64
View_Lake                    int64
View_Other                   int64
View_Pool                    int64
View_Street                  int64
Location_6th of October      int64
Location_Ain Shams           int64
Location_Al-Haram            int64
Location_Heliopolis          int64
Location_Maadi               int64
Location_Madinaty            int64
Location_Nasr City           int64
Location_New Cairo           int64
Location_Sheikh Zayed        int64
Location_Shubra              int64
dtype: object

In [ ]:
from lightgbm import LGBMRegressor
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import r2_score

In [ ]:
df_clean = df.dropna(subset=['Area', 'Bedrooms', 'Price'])

In [ ]:
# Define features and target
X = df_clean.drop('Price', axis=1)
y = df_clean['Price']

# Convert categorical features into numerical features
X = pd.get_dummies(X, drop_first=True)

# Check the new features
print("Number of features:", X.shape[1])
print(X.head())

Number of features: 28
    Area  Bedrooms  Bathrooms  Floor  YearBuilt  Seller  Payment  Finishing  \
0  120.0       2.0        3.0    3.0       2025       5        0          0
1  162.0       3.0        2.0    6.0       2024       5        0          0
2  122.0       3.0        2.0    4.0       2024       5        0          0
4  143.0       2.0        1.0    6.0       2025       5        0          1
6  145.0       3.0        3.0    2.0       2027       1        0          0

   Furnished  Parking  ...  Location_6th of October  Location_Ain Shams  \
0          1        1  ...                        0                   0
1          1        0  ...                        0                   0
2          0        1  ...                        0                   0
4          0        1  ...                        0                   0
6          1        1  ...                        1                   0

   Location_Al-Haram  Location_Heliopolis  Location_Maadi  Location_Madinaty  \
0                  0                    0               0                  0
1                  1                    0               0                  0
2                  1                    0               0                  0
4                  0                    0               1                  0
6                  0                    0               0                  0

   Location_Nasr City  Location_New Cairo  Location_Sheikh Zayed  \
0                   0                   0                      0
1                   0                   0                      0
2                   0                   0                      0
4                   0                   0                      0
6                   0                   0                      0

   Location_Shubra
0                1
1                0
2                0
4                0
6                0

[5 rows x 28 columns]

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [ ]:
model = LGBMRegressor(
    n_estimators=100,
    random_state=42,
    verbosity=-1
)

model.fit(X_train, y_train)
y_pred = model.predict(X_test)
r2 = r2_score(y_test, y_pred)

print(r2)

0.7616732313086014

In [ ]:
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
r2 = r2_score(y_test, y_pred)

print(r2)

0.7616732313086014

In [ ]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)

print("MAE:", mae)
print("MSE:", mse)
print("RMSE:", rmse)
print("R2 Score:", r2)

MAE: 1023880.6866196439
MSE: 1954900361492.6975
RMSE: 1398177.5142994889
R2 Score: 0.7616732313086014

In [ ]:
# Correlation of every feature with Price

correlation_with_price = (
    df.corr(numeric_only=True)['Price']
      .drop('Price')
      .sort_values(ascending=False)
      .to_frame(name='Correlation with Price')
)

correlation_with_price

                         Correlation with Price
View_Garden                            0.439335
Location_Sheikh Zayed                  0.429978
Location_New Cairo                     0.395738
Area                                   0.387656
View_Pool                              0.362839
Bathrooms                              0.341142
Bedrooms                               0.250023
Location_Madinaty                      0.215097
Location_Maadi                         0.183716
Location_Heliopolis                    0.157379
View_Lake                              0.110749
YearBuilt                              0.083161
Floor                                  0.074112
Finishing                              0.066516
Furnished                              0.059187
Security                               0.038614
Payment                                0.033002
Color                                  0.021008
SchoolDist                             0.018374
Parking                                0.008239
Seller                                -0.122777
Location_6th of October               -0.139371
Location_Nasr City                    -0.169536
Location_Al-Haram                     -0.256565
Location_Shubra                       -0.282689
View_Other                            -0.286886
Location_Ain Shams                    -0.298078
View_Street                           -0.406099